### ISSUE TITLE
Time left in workout lap resetting

### ISSUE THREAD

**Issue by bs** [tommyvdz/RunPowerWorkout#1]
I am seeing a pretty big bug where at some point during a workout lap the clock resets. For example, 11 min into a workout it goes from something like 19min remaining back to 30min remaining. When the lap switches the clock resets to show the correct time.

Last night it showed me I had about an hour and 50 min left when I was almost done with a 2hr run!

Thanks for all your work! <3

**Comment by tommyvdz** [comment]
Could it be possible that you have autolap turned on on your garmin watch? That could interfere with the remaining timer. I am not sure if the datafield can distinguish between a workout-lap and a lap triggered by autolap or manual lap-button press.

**Comment by bs** [comment]
I do! AutoLap is set to (the default?) of 1mi.

Wouldn't the timing be pulled from something like the [WorkoutStep](https://developer.garmin.com/connect-iq/api-docs/Toybox/Activity/WorkoutStep.html) rather than the lap? Forgive me if I'm missing something obvious ... I just took a quick glance at the code!

**Comment by bs** [comment]
Looking a bit further ... 

1. Could you use `onWorkoutStepComplete()` without dealing with laps themselves?
2. I've got the DataScreen building and running in the simulator. How do you load a structured workout to test it?

**Comment by sam-dumont** [comment]
@bs if you want to test in the simulator you can download a structured workout in fit format (from FinalSurge for instance) and load it through Simulation -> Fit Data -> Playback File.

Then you can do FIT Data -> Simulate Data and then Data Fields -> Timer -> Start Activity

**Comment by tommyvdz** [comment]
> 1. Could you use `onWorkoutStepComplete()` without dealing with laps themselves?

I’ll take a look at this, indeed sounds like a possibility!

**Comment by tommyvdz** [comment]
@bs: I just released a new version of the data field where this issue should be resolved (thanks to @samueldumont !)

**Comment by bs** [comment]
This is great, @tommyvdz + @samueldumont! I've also noticed general stability improvements. Have been using this as a daily driver the past few weeks. Was getting regular crashes before that. Thanks for all the work!
