### ISSUE TITLE
Countdown before next interval

### ISSUE THREAD

**Issue by Petr-Mi** [tommyvdz/RunPowerWorkout#15]
It would be a good countdown before the next interval, as it is in Strydy Workout.

**Comment by sam-dumont** [comment]
Hi @Petr-Mi , there is actually a display of the next interval (15s if time based, 15s*your avg pace in m/s if distance based), it alternates the remaining time, target and duration. 

Would you expect a different behaviour ?

**Comment by Petr-Mi** [comment]
Hi @samueldumont , I mean sound with countdown like in Stryd Workout. 5 second before start next interval.

**Comment by sam-dumont** [comment]
@Petr-Mi I actually don't use stryd workout but I see what you mean. I'll see what is possible :)

**Comment by sam-dumont** [comment]
It's actually a feature from the watches themselves, you can set this up and beep 5 seconds before the end of the workout. I tried and it works fine so I'm closing this
