### ISSUE TITLE
Investigate the possibility to get the power directly from Stryd via ANT+

### ISSUE THREAD

**Issue by sam-dumont** [tommyvdz/RunPowerWorkout#17]
This would allow non multisport watches to be supported

**Comment by sam-dumont** [comment]
Looks like it's possible, tried on my wife's Vivoactive 3M and could get the workout to be displayed + alerts working. Working on this on the refactor for low mem devices branch

<img src="https://user-images.githubusercontent.com/6107797/116291571-07566400-a795-11eb-8081-39a220dbf3d5.png" height="250">

**Comment by tommyvdz** [comment]
Awesome, didn’t know this was possible! Would help a lot of people.

**Comment by sam-dumont** [comment]
I sent a preview build to some people on the FB thread so we will probably get some report today. BTW @tommyvdz, I created a slack workspace, it may be a bit easier to discuss than via PRs or FB groups (so not only for us but also for other people, we got a lot of good feedback on that thread). I'll add the link to the README (https://join.slack.com/t/runpowerworkout/shared_invite/zt-ppmb361w-~tx7C56JvQ130c2b8ii_rQ)
