### ISSUE TITLE
ANT reopen mechanism??

### ISSUE THREAD

**Issue by laszlokenezpriv** [tommyvdz/RunPowerWorkout#36]
Hello, thank you for posting the source! I, as a beginner Garmin developer with a Stryd pod, find it very useful.

But I just can't find the ANT channel reopen mechanism. Is this the full code?

Best regards,
Laszlo

**Comment by sam-dumont** [comment]
Hey Lazlo, I realize we never replied, you can find the mechanism here : https://github.com/tommyvdz/RunPowerWorkout/blob/master/source-ant/PowerSensor.mc

I did not create all that by myself, I found the solution on Garmin's forums, there is a link with more details
