### ISSUE TITLE
Support for daily suggestions possible?

### ISSUE THREAD

**Issue by CPlusPlus17** [tommyvdz/RunPowerWorkout#49]
I'm manly only using the daily suggested workout, is there a way that those workouts can be supported?

**Comment by sam-dumont** [comment]
Hi @CPlusPlus17, I don't think it's feasible because the daily suggestion are pace based, not power based so it will not provide the right targets

**Comment by HaleTom** [comment]
@CPlusPlus17 I assume you mean the Garmin suggested workout, which as @samueldumont says is either pace (or alternatively HR) based.

For Stryd daily workouts, see https://github.com/tommyvdz/RunPowerWorkout/issues/55

I think this issue could be closed?

**Comment by CPlusPlus17** [comment]
Thanks for the information, seems legit. :)
