### ISSUE TITLE
Setup instructions and documetation

### ISSUE THREAD

**Issue by HaleTom** [tommyvdz/RunPowerWorkout#54]
I read [here on the Stryd Facebook group](https://github.com/tommyvdz/RunPowerWorkout):

> You need to pair your stryd as a footpod AND as a power meter. You also need to have the Stryd Zones datafield running on another screen. I realize that this is not clear, we'll adapt the doc

I couldn't see this in the README at https://github.com/tommyvdz/RunPowerWorkout

Is there another doc?

**Comment by HaleTom** [comment]
In further developments:

Stryd says that the pod should NOT be connected as an ANT+ "PWR-XXXXX" accessory, asserting that it can "cause problems, particularly with pace and distance tracking." as shown here:

https://support.stryd.com/hc/en-us/articles/360059109933-Garmin-PWR-Pairings-to-Stryd-Causing-Distance-Errors#:~:text=cause%20problems%2C%20particularly%20with%20pace%20and%20distance%20tracking.

This is ironic, because your brilliant RunPowerWorkout field requires Stryd to be connected as a PWR meter for any power data to be displayed.

I'm not seeing any distance/pace issues on my 265 with it connected as a PWR meter.

I've asked Stryd:  "If we really shouldn't connect Stryd as a PWR accessory, can you please tell me how the RPW developer should read the power like the Stryd data field does, so I can pass the info on to him in GitHub?"

**Comment by HaleTom** [comment]
In a related issue, [I'm getting 0% execution scores as judged by Garmin](https://forums.garmin.com/sports-fitness/running-multisport/f/forerunner-265-series/339221/bug-no-power-information-with-setting-power---source---accessory-only-3-issues)

Any ideas as to what may be causing this?

**Comment by sam-dumont** [comment]
> In further developments:
> 
> Stryd says that the pod should NOT be connected as an ANT+ "PWR-XXXXX" accessory, asserting that it can "cause problems, particularly with pace and distance tracking." as shown here:
> 
> [support.stryd.com/hc/en-us/articles/360059109933-Garmin-PWR-Pairings-to-Stryd-Causing-Distance-Errors#:~:text=cause%20problems%2C%20particularly%20with%20pace%20and%20distance%20tracking](https://support.stryd.com/hc/en-us/articles/360059109933-Garmin-PWR-Pairings-to-Stryd-Causing-Distance-Errors#:~:text=cause%20problems%2C%20particularly%20with%20pace%20and%20distance%20tracking).
> 
> This is ironic, because your brilliant RunPowerWorkout field requires Stryd to be connected as a PWR meter for any power data to be displayed.
> 
> I'm not seeing any distance/pace issues on my 265 with it connected as a PWR meter.
> 
> I've asked Stryd: "If we really shouldn't connect Stryd as a PWR accessory, can you please tell me how the RPW developer should read the power like the Stryd data field does, so I can pass the info on to him in GitHub?"

It is indeed not ideal to add the pod as PWR. We have no other choices right now because that's the only way to display the value. All the work here is 'unsupported' and not official, we have to work around the limitations of the Garmin ecosystem. I did not have any issue with using this datafield but it's not a 'officially supported' setup for Stryd.

Regarding the 0% execution score, it's most probably because the 'internal' workout from the watch is not really seeing the power. If you go to the standard workout screen, you'll see it stays at 0 all the time, this is why this DF is needed to execute workout with Stryd.
