### ISSUE TITLE
Using Stryd workouts with RPW

### ISSUE THREAD

**Issue by HaleTom** [tommyvdz/RunPowerWorkout#55]
I'm using one of Steve Palladino's excellent plans that are available through the Stryd Library.  Stryd app has crashed on me about 3 times, and that was only the first workout of the 11 week plan....

(I'm still on my 6 month new device forced membership, so access to these plans may be a paid feature.)

Is it somehow possible to get RPW to know about today's Stryd workout, as if it were synced from say Training Peaks?

Either way, would you consider documenting this?

Do you know of any possible work arounds to share, eg, manually recreate the workout on site X, then sync to Garmin to view in RPW.  (If you know a good value of X, I'm all ears :)

Cheers for such an awesome datafield!

**Comment by sam-dumont** [comment]
Hey @HaleTom , yes if you recreate it in FinalSurge or intervals.icu and sync to your Garmin watch then you can follow the plan. That's what I did for a while :) 

Right now the Stryd training plans are not exported to Garmin watches

**Comment by HaleTom** [comment]
Thanks very much!

I tried FS, will try intervals.icu.
