### ISSUE TITLE
Red arrow fell out of range in last workout segment

### ISSUE THREAD

**Issue by HaleTom** [tommyvdz/RunPowerWorkout#56]
Today I saw a new (and very useful) red pointy arrow at the top of the RPW display.

I found it useful because it seemed to be tracking my 10 or 30 second power, while I had the RPW white box set to track my instantaneous.

Having two time scales let me see if I had just dropped my power in the last few seconds, or if I was slacking off for a while :)

When running at a steady power, both the white box and red arrow overlapped each other, saying that I was indeed running steady for some period of time.

The Red arrow was always within the RPW power arc at the top until the last segment of my workout, when the red arrow dropped firstly down the left side

![2023-07-25-08-42-46](https://github.com/tommyvdz/RunPowerWorkout/assets/13854417/d087c29d-67d3-4784-b5be-8722b6ef4ea6)

... and then to the bottom:
![2023-07-25-08-43-16](https://github.com/tommyvdz/RunPowerWorkout/assets/13854417/9d8803bd-827e-4d7f-956f-d796da0b86c1)

Any ideas what may be causing this?  Is the red arrow drawn by RPW, or is it some Garmin artifact?

**Comment by sam-dumont** [comment]
Hi @HaleTom , this is part of the standard Garmin features, it's the heading bug when navigating. AFAIK you can enable / disable it following the instructions here : https://www8.garmin.com/manuals/webhelp/GUID-AC520B63-3C82-4266-90F6-6E9F22D5F76E/EN-US/GUID-CF95056A-4DFB-4D1B-B28F-0391E82A3541.html
