### ISSUE TITLE
Rewrite the README

### ISSUE THREAD

**Issue by sam-dumont** [tommyvdz/RunPowerWorkout#9]
- Add license for Pragati
- Add license (@tommyvdz you're the author so I suppose you have a preference for open source licenses)
- Add screenshots of various devices + states of the datafield
- Description of features support per type of devices

**Comment by sam-dumont** [comment]
resolved by #14

**Comment by tommyvdz** [comment]
Hi @samueldumont, sorry for not replying earlier. You are making impressive progress Samual, thank you so much! I’ve just release 1.2.0 to ConnectIQ. I’m not too familiar with OSS licenses, but I guess the GNU-GPL is appropriate.
